replicaCount: 1

image:
  repository: dragonmetrics/dm
  pullPolicy: Always
  tag: "API.Dragonmetrics_1233"

imagePullSecrets:
  - name: dm-dockerhub-secrets
nameOverride: "container-name" 
fullnameOverride: "dm-api"   
containerPort: "5000"
readinessProbePath: / 
livenessProbePath: / 




serviceAccount:
  create: false
  name: "default"

service:
  type: ClusterIP
  port: 5000

ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx

  hosts:
    - host: testbyken.dragonmetrics-static.com
      paths:
        - path: /
          pathType: Prefix

autoscaling:
  enabled: false
